Fix #765 from XSK
dirigiblelabs/ide-workspace pull request #5
Opened 2022-04-01 11:02 UTC by dimitarquanterall

Add New -> xsaccess file in workspace contextual menu. 
If file already exists in destination folder the option is not displayed.

2022-04-01 14:14 UTC, StanZGenchev commented
I see unneeded setTimeout functions and the 1 xsaccess file per folder does not work properly.
Will discuss later.

2022-04-04 14:41 UTC, delchev commented
- there are more file types where there is no name in it not only .xsaccess (e.g. .xspriviledges, etc.)
- these files like .xsaccess should not be processed here in this way, because they are not known in this context

2022-04-04 14:51 UTC, delchev requested changes
there are more file types where there is no name in it not only .xsaccess (e.g. .xspriviledges, etc.)
these files like .xsaccess should not be processed here in this way, because they are not known in this context

2022-04-04 14:51 UTC, delchev commented on ide-workspace/workspace.js
> +const models = ['extension', 'extensionpoint', 'edm', 'model', 'dsm', 'schema', 'bpmn', 'job', 'xsjob', 'xsaccess', 'listener', 'websocket', 'roles', 'constraints', 'table', 'view'];
xsjob and xsaccess are not known in this context
have to be done via extensions

2022-04-06 09:27 UTC, delchev approved these changes

2022-04-08 08:09 UTC, ThuF approved these changes

2022-04-08 08:09 UTC, merged